### ISSUE TITLE
Extension Breaks Remote - WSL

### ISSUE THREAD

**Issue by kenzik** [microsoft/vscode-iot-workbench#640]
Using stable or insiders with just "Remote - WSL" installed, adding "Azure IoT Device Workbench" will kill the connectivity between VS Code and the remote vs code process, leaving the workbench unusable.

Using "Remote - WSL" with **only** "Azure Account" and "Azure IoT Hub Tookit" (installed by this extension), does **not** produce the same erratic behavior. 

The source code is located in the WSL "filesystem" and the projects are being launched from bash within the project folder, eg: ```code .``` or ```code-insiders .```

Project files are irrelevant. The issue occurs within an empty project as well.

System Details:

```
Windows Build 1803.3-MAR-2019
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

```
Version: 1.36.0-insider (user setup)
Commit: 6520c22b83c0b6f168ba7de3309ffab42281e905
Date: 2019-06-19T05:19:10.147Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```
```
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by dilin-MS** [comment]
Hi, @kenzik , 

When you say : **"Azure IoT Device Workbench" will kill the connectivity between VS Code and the remote vs code process, leaving the workbench unusable.** 
Do you mean that: 
1. You install "Remote - WSL" and "Azure IoT Device Workbench" in, let's say, stable vscode; 
2. You navigate to a file path in the WSL filesystem and use `code .` to open the project in vscode; 
3. The vscode can open the project in WSL mode, **but the workbench extension is now unusable**

Is this the situation you met?

If that's the case. The reason is that the local filesystem and remote filesystem has separate extension set. Local extension will not automatically sync to remote side. You can check the [document](https://code.visualstudio.com/docs/remote/wsl#_managing-extensions).
You are supposed to install the "Azure IoT Device Workbench" extension in remote side(i.e. the wsl environment) by clicking the "Extensions" button in the open vscode wsl window and click the "Azure IoT Device Workbench"'s "install on WSL" button.

Please let me know if this is not the case or you have other problem.

**Comment by kenzik** [comment]
I may have misused the terms. Corrected and added some clarification:

...will kill the connectivity between VS Code and the remote vs code process, leaving the ~workbench~ workspace unusable.

Quick steps to reproduce from fresh install of stable: add Remote WSL; restart; ./code project-folder; install Azure IoT Device Workbench; restart; wait a few seconds and the disconnect *from wsl* will happen. After disconnect, you can't edit your code. NOTE: In insiders (as of yesterday) the code files disappear from the view after disconnect. 

![iot-workbench-issue](https://user-images.githubusercontent.com/423503/59849384-76f79e80-9335-11e9-93b5-51013bd0cc32.gif)

I noticed this after installing the extension into my otherwise rock-solid VS Code setup in order to start working with an MXChip.

**Comment by dilin-MS** [comment]
Hi @kenzik , not all extension can work without modification in remote environment. Currently our extension "Azure IoT Device Workbench" has not yet supported the remote situation. More adjustments need to be done and we are working on it. Sorry for the inconvenience and you can wait for the new release of "Azure IoT Device Workbench" which integrates with the remote extension.

**Comment by kenzik** [comment]
@dilin-MS - No worries. I just wanted to raise the issue since (1) the Remote options made it to preview in stable; and (2) it wasn't already raised. 

I'm fine working around it.

**Comment by dilin-MS** [comment]
@kenzik , thanks for your active participation.

**Comment by dilin-MS** [comment]
Current `0.10.13` version `Azure IoT Device Workbench` can be installed but cannot work properly if enable remote-wsl mode. But it will not break other extensions.
The installation failure reason is that the dependency extension `Azure Account` does not support `remote-wsl` well. We will open issue to `Azure Account`.
Close this issue since it is an external issue.

**Comment by dilin-MS** [comment]
https://github.com/microsoft/vscode-azure-account/issues/152
