### ISSUE TITLE
[IoT Workbench][Embedded Linux Project] Integrated terminal is forced to Dev Container

### ISSUE THREAD

**Issue by darenm** [microsoft/vscode-iot-workbench#742]
In VS Code, while working with an Embedded Linux workspace connected to the dev container, it seems like the integrated terminal is forced to connect directly to the dev container. While I can see the use for this, I don't seem to be able to open the WSL bash, cmd or powershell, nor does the dev container seem to have ssh available, so I have to use an external terminal to connect to my Raspberry pi.

**Comment by zunhu** [comment]
I think you don't need to use an external terminal to connect to Raspberry pi.
Remote-Containers has integrated.
![image](https://user-images.githubusercontent.com/40815873/64500148-9aa40280-d2ee-11e9-8b4a-7c0be5b488e2.png)

**Comment by darenm** [comment]
You are missing the point. I don't want to configure VScode server etc., I just want to log on to my Raspnberry Pi and run other commands, etc. I can do that at any other time. However, when using the Dev Containers I cannot use Integrated Terminals to connect to anything aside from the dev container:
![image](https://user-images.githubusercontent.com/1674843/64500388-35aec500-d27a-11e9-8959-820d71265c65.png)

Compare that to a regular C project:
![image](https://user-images.githubusercontent.com/1674843/64500621-2c722800-d27b-11e9-8b99-f14327290491.png)

**Comment by dilin-MS** [comment]
Hi, when you create an Embedded Linux project, we open the project in dev container so you are developing your application in the isolated environment(the dev container). This way you can leverage the pre-installed tools such as azure-sdk, cross-compile toolchain, etc.

Because our dev container does not pre-installed ssh server, you cannot connect to your RPI inside dev container. The expected practice is you develop and deploy your code to your RPI using our "deploy" command, which will connect to you RPI for you. 

If you would like to connect to your RPI through terminal, you can either use another VS Code instance or use `Remote-Container: Reopen locally` to go back to local environment.
