### ISSUE TITLE
Couldn't generate code from the DevKit pnp schema from IoT Central

### ISSUE THREAD

**Issue by arthma** [microsoft/vscode-iot-workbench#878]
Repo step:
1. Export the pnp schema from IoT central for MXChip IoT DevKit
2. Run 'Generate Device Code Stub.' on IoT Device Workbench extension for VS Code, fails with error
![image](https://user-images.githubusercontent.com/7304450/70909431-715ee500-2048-11ea-8ea4-d416cce514fa.png)

**Comment by dooriya** [comment]
Thanks @arthma for your feedback.

The root cause of the error is due to IoT Central uses a device template which is not align with[ official DTDL](http://aka.ms/dtdl). An extra "contents" property is not supported in a DCM file currently, We've already expose this issue to Central team and they will fix this template format in the upcoming release.

If your scenario is to generate and customize PnP code for IoT DevKit, please use the [pre-certified DCM file ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepo.azureiotrepository.com%2Fmodels%2Furn%3Amxchip%3Amxchip_iot_devkit%3A1%3Fapi-version%3D2019-07-01-preview%26expand%3Dtrue&data=02%7C01%7Cdol%40microsoft.com%7Ca9770b28e4d94d36cb8308d7837deaea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637122449193395947&sdata=mp1UhyLk8I%2FuxxggMEcKemITe7FCZ%2BBiCjqq2TDZpP8%3D&reserved=0)for DevKit from public model repository.

Please feel free to re-open this issue if this still occur with the official DevKit DCM.
 
Thanks,
Dooriya
